// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypcriklxpxylcbsstzrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwY3Jpa2x4cHh5bGNic3N0enJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODc1MjgsImV4cCI6MjA2MDY2MzUyOH0.74ZZfj5Q04nJ6b_4VtoV9p3CCHPjHOiHkpqpcEmLNxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);